// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwzlxnfftzeqbtptyqzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3emx4bmZmdHplcWJ0cHR5cXp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwMzgzMzYsImV4cCI6MjA1NTYxNDMzNn0.n4DeTkZ4bswfBwMVVdtlEL0BobOecLRc1m0YBDj1Z_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);